services:
  - type: web
    name: telegram-bot-webhook
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: python3 render_webhook_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1

      
startCommand: python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload render_web:app

envVars:
  - key: PORT          # ← Port automatique Render.com
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
